# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementaryParticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mass', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField()),
                ('projectile_object_id', models.PositiveIntegerField()),
                ('product_one_object_id', models.PositiveIntegerField()),
                ('product_two_object_id', models.PositiveIntegerField()),
                ('product_three_object_id', models.PositiveIntegerField()),
                ('product_one_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_one_content', to='contenttypes.ContentType')),
                ('product_three_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_three_content', to='contenttypes.ContentType')),
                ('product_two_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_two_content', to='contenttypes.ContentType')),
                ('projectile_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectile_content', to='contenttypes.ContentType')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_content', to='contenttypes.ContentType')),
            ],
        ),
    ]
