# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0015_auto_20180216_1129'),
        ('nucreactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementary_particle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nucreactions.ElementaryParticle')),
                ('isotope', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isotopes.Isotope')),
            ],
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_one_content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_one_object_id',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_three_content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_three_object_id',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_two_content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product_two_object_id',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='projectile_content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='projectile_object_id',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='target_object_id',
        ),
        migrations.AddField(
            model_name='reaction',
            name='product_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_one', to='nucreactions.ReactionsField'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='product_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_three', to='nucreactions.ReactionsField'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='product_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_two', to='nucreactions.ReactionsField'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='projectile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectile', to='nucreactions.ReactionsField'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='nucreactions.ReactionsField'),
        ),
    ]
