# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0002_auto_20180328_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='product_one',
            new_name='_product_one',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='product_three',
            new_name='_product_three',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='product_two',
            new_name='_product_two',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='projectile',
            new_name='_projectile',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='target',
            new_name='_target',
        ),
    ]
