# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0003_auto_20180328_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reactionsfield',
            name='radiation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_radiation', to='nucreactions.ElementaryParticle'),
        ),
        migrations.AlterField(
            model_name='reactionsfield',
            name='elementary_particle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_elementary_particle', to='nucreactions.ElementaryParticle'),
        ),
        migrations.AlterField(
            model_name='reactionsfield',
            name='isotope',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_isotope', to='isotopes.Isotope'),
        ),
    ]
