# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0004_auto_20180329_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionsfield',
            name='radiation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_radiation', to='nucreactions.Radiation'),
        ),
    ]
