# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0005_auto_20180329_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementaryparticle',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='radiation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
