# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0009_auto_20180501_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionsfield',
            name='elementary_particle',
        ),
        migrations.RemoveField(
            model_name='reactionsfield',
            name='isotope',
        ),
        migrations.RemoveField(
            model_name='reactionsfield',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='reactionsfield',
            name='radiation',
        ),
    ]
