# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elementaryparticles', '0001_initial'),
        ('radiations', '0001_initial'),
        ('isotopes', '0015_auto_20180216_1129'),
        ('nucreactions', '0010_auto_20180501_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionsfield',
            name='elementary_particle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_elementary_particle', to='elementaryparticles.ElementaryParticle'),
        ),
        migrations.AddField(
            model_name='reactionsfield',
            name='isotope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_isotope', to='isotopes.Isotope'),
        ),
        migrations.AddField(
            model_name='reactionsfield',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reactionsfield',
            name='radiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_radiation', to='radiations.Radiation'),
        ),
    ]
