# Generated by Django 2.0.6 on 2018-07-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucreactions', '0011_auto_20180501_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['_target']},
        ),
        migrations.AlterModelOptions(
            name='reactionsfield',
            options={'ordering': ['isotope', 'elementary_particle', 'radiation']},
        ),
    ]
