# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('isotope_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isotopes.Isotope')),
            ],
            bases=('isotopes.isotope',),
        ),
        migrations.CreateModel(
            name='Unstable',
            fields=[
                ('isotope_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isotopes.Isotope')),
            ],
            bases=('isotopes.isotope',),
        ),
        migrations.RemoveField(
            model_name='neutprottuple',
            name='mode',
        ),
        migrations.DeleteModel(
            name='NeutProtTupleParts',
        ),
    ]
