# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0004_auto_20171204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='neutprottuple',
            name='neutrons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neutprottuple',
            name='protons',
            field=models.IntegerField(default=0),
        ),
    ]
