# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0007_auto_20171218_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stable',
            name='isotope_ptr',
        ),
        migrations.RemoveField(
            model_name='unstable',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='unstable',
            name='isotope_ptr',
        ),
        migrations.AddField(
            model_name='isotope',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isotopes.Isotope'),
        ),
        migrations.AddField(
            model_name='isotope',
            name='iso_type',
            field=models.CharField(choices=[('S', 'Stable'), ('U', 'Unstable')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Stable',
        ),
        migrations.DeleteModel(
            name='Unstable',
        ),
    ]
