# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0008_auto_20180116_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isotope',
            name='iso_id',
        ),
    ]
