# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0012_auto_20180123_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuclearStructureTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_1', to='isotopes.NeutProtTuple')),
                ('shell_10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_10', to='isotopes.NeutProtTuple')),
                ('shell_11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_11', to='isotopes.NeutProtTuple')),
                ('shell_12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_12', to='isotopes.NeutProtTuple')),
                ('shell_13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_13', to='isotopes.NeutProtTuple')),
                ('shell_14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_14', to='isotopes.NeutProtTuple')),
                ('shell_15', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_15', to='isotopes.NeutProtTuple')),
                ('shell_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_2', to='isotopes.NeutProtTuple')),
                ('shell_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_3', to='isotopes.NeutProtTuple')),
                ('shell_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_4', to='isotopes.NeutProtTuple')),
                ('shell_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_5', to='isotopes.NeutProtTuple')),
                ('shell_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_6', to='isotopes.NeutProtTuple')),
                ('shell_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_7', to='isotopes.NeutProtTuple')),
                ('shell_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_8', to='isotopes.NeutProtTuple')),
                ('shell_9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shell_9', to='isotopes.NeutProtTuple')),
            ],
        ),
    ]
