# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0014_auto_20180130_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_1',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_10',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_11',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_12',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_13',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_14',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_15',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_16',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_17',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_2',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_3',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_4',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_5',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_6',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_7',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_8',
        ),
        migrations.RemoveField(
            model_name='nuclearstructuretable',
            name='shell_9',
        ),
        migrations.DeleteModel(
            name='NuclearStructureTable',
        ),
    ]
