# Generated by Django 2.0.6 on 2018-07-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isotopes', '0015_auto_20180216_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeutProtTuple',
        ),
    ]
